
var headerText = '<div><header><div class="container-fluid header"><div class="header__top row"><div class="header__top__logo  logo col-sm-5 logo col-md-4"><a class="logo-link" href="../../index.html" title="Travelport" rel="home"><img class="img-responsive" src="../../img/logo/logo.png" alt="Travelport"></a></div><div class="header__top__nav col-sm-7 logo col-md-8"><ul class="header__ul"><li class="header__top__li"><a href="../../index.html" >Travelport</a></li><li class="header__top__li"><a class="active__link" href="../news/news.html">Новости</a></li><li class="header__top__li"><a href="../contact/contact.html">Контакты</a></li></ul></div></div><div class="header__bot row"><div class="header__bot__menu col-sm-12"><ul class="nav nav-pills bot__menu"><li class="nav-item dropdown"><a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#"><i class="fas fa-caret-down"></i> Продукты и сервисы </a><div class="dropdown-menu products"><a class="dropdown-item" href="../t_smartpoint/t_smartpoint.html">Travelport Smartpoint</a><a class="dropdown-item" href="../t_a_shopping/t_a_shopping.html">Travelport Aggregated shopping</a><a class="dropdown-item" href="../t_s_c_console/t_s_c_console.html">Travelport Search Control Console</a><a class="dropdown-item" href="../t_q_c_console/t_q_c_console.html">Travelport Queue Control Console</a><a class="dropdown-item" href="../t_e-tracker/t_e-tracker.html">Travelport E-Tracker</a><a class="dropdown-item" href="../t_b_feed/t_b_feed.html">Travelport Booking Feed</a><a class="dropdown-item" href="../t_e-princing/t_e-princing.html">Travelport e-Pricing</a><a class="dropdown-item" href="../g_e_manager/g_e_manager.html">Global Exchange Manager</a><a class="dropdown-item" href="../t_viewtrip/t_viewtrip.html">Travelport Viewtrip</a></div></li><li class=""><a class="nav-link" href="../connection/connection.html">Подключениe</a></li><li class=""><a class="nav-link" href="../course/course.html">Курсы</a></li></ul></div></div></div></header></div>';

function setHeader() {
var header = document.createElement('div');
header.innerHTML = headerText;
document.body.insertAdjacentElement('beforebegin', header);
}

setHeader();